fix ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -405,7 +405,7 @@ jobs:
     test-frontend-integration:
         name: Frontend Integration Tests
         runs-on: ubuntu-latest
-        needs: [changes, build, test-frontend-unit, prepare-sample-media]
+        needs: [changes, build-binary-pr, test-frontend-unit, prepare-sample-media]
         if: |
             github.event_name == 'pull_request' &&
             (needs.test-frontend-unit.result == 'success' || needs.test-frontend-unit.result == 'skipped') &&
@@ -546,7 +546,8 @@ jobs:
                 test-integration,
                 test-frontend-unit,
                 test-frontend-integration,
-                build,
+                build-binary-check,
+                build-binary-pr,
             ]
         if: |
             always() &&
@@ -556,7 +557,8 @@ jobs:
             (needs.test-integration.result == 'success' || needs.test-integration.result == 'skipped') &&
             (needs.test-frontend-unit.result == 'success' || needs.test-frontend-unit.result == 'skipped') &&
             (needs.test-frontend-integration.result == 'success' || needs.test-frontend-integration.result == 'skipped') &&
-            (needs.build.result == 'success' || needs.build.result == 'skipped') &&
+            (needs.build-binary-check.result == 'success' || needs.build-binary-check.result == 'skipped') &&
+            (needs.build-binary-pr.result == 'success' || needs.build-binary-pr.result == 'skipped') &&
             (
               (github.event_name == 'push' && needs.changes.outputs.docker-related == 'true') ||
               (github.event_name == 'pull_request')
@@ -582,7 +584,8 @@ jobs:
                 test-integration,
                 test-frontend-unit,
                 test-frontend-integration,
-                build,
+                build-binary-pr,
+                build-binary-check,
             ]
         if: |
             always() &&
@@ -592,7 +595,8 @@ jobs:
             (needs.test-integration.result == 'success' || needs.test-integration.result == 'skipped') &&
             (needs.test-frontend-unit.result == 'success' || needs.test-frontend-unit.result == 'skipped') &&
             (needs.test-frontend-integration.result == 'success' || needs.test-frontend-integration.result == 'skipped') &&
-            (needs.build.result == 'success' || needs.build.result == 'skipped') &&
+            (needs.build-binary-check.result == 'success' || needs.build-binary-check.result == 'skipped') &&
+            (needs.build-binary-pr.result == 'success' || needs.build-binary-pr.result == 'skipped') &&
             (
               (github.event_name == 'push' && needs.changes.outputs.docker-related == 'true') ||
               (github.event_name == 'pull_request')
@@ -615,7 +619,8 @@ jobs:
             [
                 lint,
                 lint-frontend,
-                build,
+                build-binary-check,
+                build-binary-pr,
                 test-unit,
                 test-integration,
                 test-race,
@@ -637,8 +642,12 @@ jobs:
                     echo "Frontend lint failed"
                     exit 1
                   fi
-                  if [[ "${{ needs.build.result }}" == "failure" ]]; then
-                    echo "Build failed"
+                  if [[ "${{ needs.build-binary-check.result }}" == "failure" ]]; then
+                    echo "Build binary check failed"
+                    exit 1
+                  fi
+                  if [[ "${{ needs.build-binary-pr.result }}" == "failure" ]]; then
+                    echo "Build binary PR failed"
                     exit 1
                   fi
                   if [[ "${{ needs.test-unit.result }}" == "failure" ]]; then
